[package]
name = "fibers"
version = "0.1.0"
authors = ["Takeru Ohta <takeru_ohta@dwango.co.jp>"]
publish = false

[dependencies]
mio = "0.6"
futures = "0.1"
lazy_static = "0.1"
splay_tree = "0.2"
num_cpus = "1.1"

[dev-dependencies]
clap = "2.18"
handy_io = "0.1"
